print("my English name is tom:")
print("#######   #     #         #")
print("   #    #   #   # #     # #")
print("   #   #     #  #  #   #  #")
print("   #    #   #   #   # #   #")
print("   #      #     #    #    #")
